apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 624376450453.dkr.ecr.us-east-1.amazonaws.com/underwaterapp
  newName: 624376450453.dkr.ecr.us-east-1.amazonaws.com/underwaterapp
  newTag: 1.0.4

resources:
- defi-automation-api.yaml
